#! /bin/sh
picom --experimental-backends &
eww daemon &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
#kitty -e vim ~/study/revise.md +Goyo &
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4

bspc config border_width         3
bspc config window_gap          35
bspc config top_padding         45
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "#b4f9f8"
#bspc config active_border_color "#b04fff"
#bspc config focused_border_color "#d7a6ff"
bspc config focused_border_color "#bb9af7"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


bspc rule -a discord desktop=^4
bspc rule -a spotify desktop=^3
bspc rule -a firefox desktop=^1
bspc rule -a Code desktop=^2
bspc rule -a Emacs state=tiled
