format = """$directory$git_branch$python """
palette = "kanagawa"
add_newline = false


[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.kanagawa]
red = '#e46876'
pink = '#d27e99'
green = '#98bb6c'
aqua = '#7aa89f'
yellow = '#e6c384'
blue = '#7fb4ca'
light_violet = '#938aa9'
violet = '#957fbb'

[directory]
format = "[ ](fg:aqua)[ $path]($style)(fg:overlay)"
style = "fg:aqua bold"
truncation_length = 2
truncation_symbol = ""
use_logical_path = true

[character]
success_symbol = "[󱪁](blue bold)"
error_symbol = "[󱪁](red bold)"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "(fg:overlay)[ $symbol $branch]($style)(fg:overlay)"
style = "fg:green"
symbol = ""

[time]
disabled = false
format = "(fg:overlay)[ $time 󰴈 ]($style)(fg:overlay)"
style = "fg:gold"
time_format = "%H:%M"
use_12hr = false

[username]
disabled = true
format = "[ $user](fg:yellow)"
show_always = true

[python]
detect_extensions=[]
style = 'fg:yellow'
symbol = ' '
format = ' [${symbol}$virtualenv]($style)'
